const http=require('http')
//using the createServer function we can create the basic http server using the http module which is internally provided by the node 
//this function returns a server object and takes the callback argument ;

const PORT=3000; // CREATION OF PORT
// this function can create the server but not started it

const server =http.createServer(function listener(request,response){
    //using the request argument you can see the incoming http request
    //using the reaponse we will be able to configure the response fot the http request
    // this function is going to listen to all the request we make to the server
     console.log("request recived")

    // console.log("incoming request details",request)
    // console.log("outgoing response details",response)
    // now if the url end with/home i have to send the output
    // to check the http method we are using
    // console 
    // you can check the api on the postman 
    console.log(request.method)
    if(request.url=='/home')
    {
        response.end("welcome to home ")
        // what this function does is this function end the writible string of response stream 
        // so no new date is wrriten and print  the argument on the screen
        // when youu send the end argument you have to send this in the form string because browser
        // automatically convert it to the html
    }



    // // if somebody at any point of time hit any request to my server just print this line 
})
// any process is uniquely identified by the port number is someone want to communicate with
// our http server the he require the ip but at that ip multiple process can be in the runninng this.state.
// to communicate with the correct process we requir the port number.
//so what we have to do is we have to bind this server object with the port number
let i=0
server.listen(PORT,function exec(){
    // once we succesfully bot up the server on the given port this callback is called 
   
    console.log("server is up and runnig on port:",PORT)
    
   
    
})
// this function is going to start the listening process on the server
// this listen function is takeing frist argument as the port number which is a type of number 
// but sometimes people pass the string but javascript automatically does the type cooersion
//apart from the port this listen function require the callback 

//part -2
// how can we connect this server with the clint or how the request is generated by the clieny?
// how you can connect to this port with your browser while your browsar and server they both 
// running on the same machine
// and we have not hoseted the server on the internet yet
// this server is currently running on the my machine not on the internet which means that that
// is any one want to send request to this server has to send the request to my machine
// this server is only accesible to your own machine at any point of time you want to communicate 
// with your own machine what ip address you should give=127.0.0.1
// is the standard address to loop back to your machine(loopback=localhost)
// at this address you are trying to communicate with your own machine 127.0.0.1:3000(port number)

//part -3(request made)
// what happens when you google this ip your computer is making request to it own port 3000
// and it works as a server which recives the request and send back the response 
